name: asset_resolver
description: Helps you to generate a .dart file that contains all assets according to `pubspec.yaml`.
version: 0.0.1
homepage: https://github.com/wkcdeie/asset_resolver

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.3.0
  yaml: ^3.1.1
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  path: ^1.8.3
